### ISSUE TITLE
pipeline翻译成流水线是不是更好？

### ISSUE THREAD

**Issue by abcvav** [schrodingercatss/tuning_playbook_zh_cn#1]
pipeline翻译成管道容易让人摸不着头脑

**Comment by NingJay** [comment]
![Screenshot_20230527_180833_com yandex browser](https://github.com/schrodingercatss/tuning_playbook_zh_cn/assets/88469454/d93f99f1-dcea-4210-9014-58e109599f22)
理论上管道-过滤器模型
流水线-过滤器不是很对吧
