### ISSUE TITLE
我感觉这个部分应该是“上限”，不是“上线”

### ISSUE THREAD

**Issue by lovekang3344** [schrodingercatss/tuning_playbook_zh_cn#2]
![image](https://github.com/schrodingercatss/tuning_playbook_zh_cn/assets/101037867/8e915bc3-470a-4d48-879f-47e5b55c0ae4)
我觉得"上线“可以改成”上限“，这样好像更加符合我们的认知。

**Comment by NingJay** [comment]
上线: 更新配置
上限: 最大的限制

**Comment by schrodingercatss** [comment]
原文：We call it a launch when we update our best configuration (which may or may not correspond to an actual launch of a production model).  这里的「上线」一词对应的是「launch」
